#
# ROS bag dataset config
# 
measurements:
    lidar:
        #topic_name: /kitti/velo/pointcloud
        topic_name: /velodyne_points
        frame_id: velo_link
        queue_size: 100000
    imu:
        #topic_name: /kitti/oxts/imu
        topic_name: /imu/data
        frame_id: imu_link
        queue_size: 1000000
    gnss:
        topic_name: /kitti/oxts/gps/fix
        frame_id: imu_link
        queue_size: 1000000

    